// Every indexable route the static export ships, minus build artefacts
// (_shell/_sitemap/google-verification) and the URL-encoded duplicate twins.
export const ROUTES = [
  '/',
  '/explore',
  '/favorites',
  '/profile',
  '/sell',
  '/search',
  '/brands',
  '/about',
  '/contact',
  '/services',
  '/insurance',
  '/help',
  '/safety',
  '/guidelines',
  '/how-we-verify',
  '/buyer-protection',
  '/careers',
  '/press',
  '/accessibility',
  '/privacy',
  '/terms',
  '/cookies',
  '/report',
  '/delete',
  '/auth/login',
  '/auth/login-form',
  '/auth/register',
  '/auth/verify-otp',
  '/messages',
  '/order',
  '/history',
  '/listings',
  '/notifications',
  '/settings/account',
  '/settings/notifications',
  '/settings/privacy',
  '/category/petrol-car',
  '/category/electric-car',
  '/category/motorcycle',
];

// The four widths the user asked to be judged under.
export const VIEWPORTS = [
  { name: 'mobile-390',  width: 390,  height: 844 },
  { name: 'tablet-768',  width: 768,  height: 1024 },
  { name: 'laptop-1280', width: 1280, height: 800 },
  { name: 'desktop-1920', width: 1920, height: 1080 },
];
