// Country data with correct flag emojis
export const countryData = [
  { code: "RW", name: "Rwanda", flag: "https://flagcdn.com/w40/rw.png", dialCode: "+250", maxLength: 9 },
  { code: "AD", name: "Andorra", flag: "https://flagcdn.com/w40/ad.png", dialCode: "+376", maxLength: 6 },
  { code: "AE", name: "United Arab Emirates", flag: "https://flagcdn.com/w40/ae.png", dialCode: "+971", maxLength: 9 },
  { code: "AF", name: "Afghanistan", flag: "https://flagcdn.com/w40/af.png", dialCode: "+93", maxLength: 9 },
  { code: "AG", name: "Antigua and Barbuda", flag: "https://flagcdn.com/w40/ag.png", dialCode: "+1268", maxLength: 7 },
  { code: "AI", name: "Anguilla", flag: "https://flagcdn.com/w40/ai.png", dialCode: "+1264", maxLength: 7 },
  { code: "AL", name: "Albania", flag: "https://flagcdn.com/w40/al.png", dialCode: "+355", maxLength: 9 },
  { code: "AM", name: "Armenia", flag: "https://flagcdn.com/w40/am.png", dialCode: "+374", maxLength: 8 },
  { code: "AO", name: "Angola", flag: "https://flagcdn.com/w40/ao.png", dialCode: "+244", maxLength: 9 },
  { code: "AQ", name: "Antarctica", flag: "https://flagcdn.com/w40/aq.png", dialCode: "+672", maxLength: 6 },
  { code: "AR", name: "Argentina", flag: "https://flagcdn.com/w40/ar.png", dialCode: "+54", maxLength: 10 },
  { code: "AS", name: "American Samoa", flag: "https://flagcdn.com/w40/as.png", dialCode: "+1684", maxLength: 7 },
  { code: "AT", name: "Austria", flag: "https://flagcdn.com/w40/at.png", dialCode: "+43", maxLength: 11 },
  { code: "AU", name: "Australia", flag: "https://flagcdn.com/w40/au.png", dialCode: "+61", maxLength: 9 },
  { code: "AW", name: "Aruba", flag: "https://flagcdn.com/w40/aw.png", dialCode: "+297", maxLength: 7 },
  { code: "AX", name: "Åland Islands", flag: "https://flagcdn.com/w40/ax.png", dialCode: "+358", maxLength: 10 },
  { code: "AZ", name: "Azerbaijan", flag: "https://flagcdn.com/w40/az.png", dialCode: "+994", maxLength: 9 },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w40/ba.png", dialCode: "+387", maxLength: 8 },
  { code: "BB", name: "Barbados", flag: "https://flagcdn.com/w40/bb.png", dialCode: "+1246", maxLength: 7 },
  { code: "BD", name: "Bangladesh", flag: "https://flagcdn.com/w40/bd.png", dialCode: "+880", maxLength: 10 },
  { code: "BE", name: "Belgium", flag: "https://flagcdn.com/w40/be.png", dialCode: "+32", maxLength: 9 },
  { code: "BF", name: "Burkina Faso", flag: "https://flagcdn.com/w40/bf.png", dialCode: "+226", maxLength: 8 },
  { code: "BG", name: "Bulgaria", flag: "https://flagcdn.com/w40/bg.png", dialCode: "+359", maxLength: 9 },
  { code: "BH", name: "Bahrain", flag: "https://flagcdn.com/w40/bh.png", dialCode: "+973", maxLength: 8 },
  { code: "BI", name: "Burundi", flag: "https://flagcdn.com/w40/bi.png", dialCode: "+257", maxLength: 8 },
  { code: "BJ", name: "Benin", flag: "https://flagcdn.com/w40/bj.png", dialCode: "+229", maxLength: 8 },
  { code: "BL", name: "Saint Barthélemy", flag: "https://flagcdn.com/w40/bl.png", dialCode: "+590", maxLength: 9 },
  { code: "BM", name: "Bermuda", flag: "https://flagcdn.com/w40/bm.png", dialCode: "+1441", maxLength: 7 },
  { code: "BN", name: "Brunei", flag: "https://flagcdn.com/w40/bn.png", dialCode: "+673", maxLength: 7 },
  { code: "BO", name: "Bolivia", flag: "https://flagcdn.com/w40/bo.png", dialCode: "+591", maxLength: 8 },
  { code: "BQ", name: "Caribbean Netherlands", flag: "https://flagcdn.com/w40/bq.png", dialCode: "+599", maxLength: 7 },
  { code: "BR", name: "Brazil", flag: "https://flagcdn.com/w40/br.png", dialCode: "+55", maxLength: 11 },
  { code: "BS", name: "Bahamas", flag: "https://flagcdn.com/w40/bs.png", dialCode: "+1242", maxLength: 7 },
  { code: "BT", name: "Bhutan", flag: "https://flagcdn.com/w40/bt.png", dialCode: "+975", maxLength: 8 },
  { code: "BV", name: "Bouvet Island", flag: "https://flagcdn.com/w40/bv.png", dialCode: "+47", maxLength: 8 },
  { code: "BW", name: "Botswana", flag: "https://flagcdn.com/w40/bw.png", dialCode: "+267", maxLength: 8 },
  { code: "BY", name: "Belarus", flag: "https://flagcdn.com/w40/by.png", dialCode: "+375", maxLength: 9 },
  { code: "BZ", name: "Belize", flag: "https://flagcdn.com/w40/bz.png", dialCode: "+501", maxLength: 7 },
  { code: "CA", name: "Canada", flag: "https://flagcdn.com/w40/ca.png", dialCode: "+1", maxLength: 10 },
  { code: "CC", name: "Cocos Islands", flag: "https://flagcdn.com/w40/cc.png", dialCode: "+61", maxLength: 9 },
  { code: "CD", name: "DR Congo", flag: "https://flagcdn.com/w40/cd.png", dialCode: "+243", maxLength: 9 },
  { code: "CF", name: "Central African Republic", flag: "https://flagcdn.com/w40/cf.png", dialCode: "+236", maxLength: 8 },
  { code: "CG", name: "Republic of the Congo", flag: "https://flagcdn.com/w40/cg.png", dialCode: "+242", maxLength: 9 },
  { code: "CH", name: "Switzerland", flag: "https://flagcdn.com/w40/ch.png", dialCode: "+41", maxLength: 9 },
  { code: "CI", name: "Côte d'Ivoire", flag: "https://flagcdn.com/w40/ci.png", dialCode: "+225", maxLength: 10 },
  { code: "CK", name: "Cook Islands", flag: "https://flagcdn.com/w40/ck.png", dialCode: "+682", maxLength: 5 },
  { code: "CL", name: "Chile", flag: "https://flagcdn.com/w40/cl.png", dialCode: "+56", maxLength: 9 },
  { code: "CM", name: "Cameroon", flag: "https://flagcdn.com/w40/cm.png", dialCode: "+237", maxLength: 9 },
  { code: "CN", name: "China", flag: "https://flagcdn.com/w40/cn.png", dialCode: "+86", maxLength: 11 },
  { code: "CO", name: "Colombia", flag: "https://flagcdn.com/w40/co.png", dialCode: "+57", maxLength: 10 },
  { code: "CR", name: "Costa Rica", flag: "https://flagcdn.com/w40/cr.png", dialCode: "+506", maxLength: 8 },
  { code: "CU", name: "Cuba", flag: "https://flagcdn.com/w40/cu.png", dialCode: "+53", maxLength: 8 },
  { code: "CV", name: "Cape Verde", flag: "https://flagcdn.com/w40/cv.png", dialCode: "+238", maxLength: 7 },
  { code: "CW", name: "Curaçao", flag: "https://flagcdn.com/w40/cw.png", dialCode: "+599", maxLength: 8 },
  { code: "CX", name: "Christmas Island", flag: "https://flagcdn.com/w40/cx.png", dialCode: "+61", maxLength: 9 },
  { code: "CY", name: "Cyprus", flag: "https://flagcdn.com/w40/cy.png", dialCode: "+357", maxLength: 8 },
  { code: "CZ", name: "Czech Republic", flag: "https://flagcdn.com/w40/cz.png", dialCode: "+420", maxLength: 9 },
  { code: "DE", name: "Germany", flag: "https://flagcdn.com/w40/de.png", dialCode: "+49", maxLength: 11 },
  { code: "DJ", name: "Djibouti", flag: "https://flagcdn.com/w40/dj.png", dialCode: "+253", maxLength: 8 },
  { code: "DK", name: "Denmark", flag: "https://flagcdn.com/w40/dk.png", dialCode: "+45", maxLength: 8 },
  { code: "DM", name: "Dominica", flag: "https://flagcdn.com/w40/dm.png", dialCode: "+1767", maxLength: 7 },
  { code: "DO", name: "Dominican Republic", flag: "https://flagcdn.com/w40/do.png", dialCode: "+1", maxLength: 10 },
  { code: "DZ", name: "Algeria", flag: "https://flagcdn.com/w40/dz.png", dialCode: "+213", maxLength: 9 },
  { code: "EC", name: "Ecuador", flag: "https://flagcdn.com/w40/ec.png", dialCode: "+593", maxLength: 9 },
  { code: "EE", name: "Estonia", flag: "https://flagcdn.com/w40/ee.png", dialCode: "+372", maxLength: 8 },
  { code: "EG", name: "Egypt", flag: "https://flagcdn.com/w40/eg.png", dialCode: "+20", maxLength: 10 },
  { code: "EH", name: "Western Sahara", flag: "https://flagcdn.com/w40/eh.png", dialCode: "+212", maxLength: 9 },
  { code: "ER", name: "Eritrea", flag: "https://flagcdn.com/w40/er.png", dialCode: "+291", maxLength: 7 },
  { code: "ES", name: "Spain", flag: "https://flagcdn.com/w40/es.png", dialCode: "+34", maxLength: 9 },
  { code: "ET", name: "Ethiopia", flag: "https://flagcdn.com/w40/et.png", dialCode: "+251", maxLength: 9 },
  { code: "FI", name: "Finland", flag: "https://flagcdn.com/w40/fi.png", dialCode: "+358", maxLength: 10 },
  { code: "FJ", name: "Fiji", flag: "https://flagcdn.com/w40/fj.png", dialCode: "+679", maxLength: 7 },
  { code: "FK", name: "Falkland Islands", flag: "https://flagcdn.com/w40/fk.png", dialCode: "+500", maxLength: 5 },
  { code: "FM", name: "Micronesia", flag: "https://flagcdn.com/w40/fm.png", dialCode: "+691", maxLength: 7 },
  { code: "FO", name: "Faroe Islands", flag: "https://flagcdn.com/w40/fo.png", dialCode: "+298", maxLength: 6 },
  { code: "FR", name: "France", flag: "https://flagcdn.com/w40/fr.png", dialCode: "+33", maxLength: 10 },
  { code: "GA", name: "Gabon", flag: "https://flagcdn.com/w40/ga.png", dialCode: "+241", maxLength: 8 },
  { code: "GB", name: "United Kingdom", flag: "https://flagcdn.com/w40/gb.png", dialCode: "+44", maxLength: 10 },
  { code: "GD", name: "Grenada", flag: "https://flagcdn.com/w40/gd.png", dialCode: "+1473", maxLength: 7 },
  { code: "GE", name: "Georgia", flag: "https://flagcdn.com/w40/ge.png", dialCode: "+995", maxLength: 9 },
  { code: "GF", name: "French Guiana", flag: "https://flagcdn.com/w40/gf.png", dialCode: "+594", maxLength: 9 },
  { code: "GG", name: "Guernsey", flag: "https://flagcdn.com/w40/gg.png", dialCode: "+44", maxLength: 10 },
  { code: "GH", name: "Ghana", flag: "https://flagcdn.com/w40/gh.png", dialCode: "+233", maxLength: 9 },
  { code: "GI", name: "Gibraltar", flag: "https://flagcdn.com/w40/gi.png", dialCode: "+350", maxLength: 8 },
  { code: "GL", name: "Greenland", flag: "https://flagcdn.com/w40/gl.png", dialCode: "+299", maxLength: 6 },
  { code: "GM", name: "Gambia", flag: "https://flagcdn.com/w40/gm.png", dialCode: "+220", maxLength: 7 },
  { code: "GN", name: "Guinea", flag: "https://flagcdn.com/w40/gn.png", dialCode: "+224", maxLength: 9 },
  { code: "GP", name: "Guadeloupe", flag: "https://flagcdn.com/w40/gp.png", dialCode: "+590", maxLength: 9 },
  { code: "GQ", name: "Equatorial Guinea", flag: "https://flagcdn.com/w40/gq.png", dialCode: "+240", maxLength: 9 },
  { code: "GR", name: "Greece", flag: "https://flagcdn.com/w40/gr.png", dialCode: "+30", maxLength: 10 },
  { code: "GS", name: "South Georgia", flag: "https://flagcdn.com/w40/gs.png", dialCode: "+500", maxLength: 5 },
  { code: "GT", name: "Guatemala", flag: "https://flagcdn.com/w40/gt.png", dialCode: "+502", maxLength: 8 },
  { code: "GU", name: "Guam", flag: "https://flagcdn.com/w40/gu.png", dialCode: "+1671", maxLength: 7 },
  { code: "GW", name: "Guinea-Bissau", flag: "https://flagcdn.com/w40/gw.png", dialCode: "+245", maxLength: 7 },
  { code: "GY", name: "Guyana", flag: "https://flagcdn.com/w40/gy.png", dialCode: "+592", maxLength: 7 },
  { code: "HK", name: "Hong Kong", flag: "https://flagcdn.com/w40/hk.png", dialCode: "+852", maxLength: 8 },
  { code: "HM", name: "Heard Island", flag: "https://flagcdn.com/w40/hm.png", dialCode: "+672", maxLength: 6 },
  { code: "HN", name: "Honduras", flag: "https://flagcdn.com/w40/hn.png", dialCode: "+504", maxLength: 8 },
  { code: "HR", name: "Croatia", flag: "https://flagcdn.com/w40/hr.png", dialCode: "+385", maxLength: 9 },
  { code: "HT", name: "Haiti", flag: "https://flagcdn.com/w40/ht.png", dialCode: "+509", maxLength: 8 },
  { code: "HU", name: "Hungary", flag: "https://flagcdn.com/w40/hu.png", dialCode: "+36", maxLength: 9 },
  { code: "ID", name: "Indonesia", flag: "https://flagcdn.com/w40/id.png", dialCode: "+62", maxLength: 11 },
  { code: "IE", name: "Ireland", flag: "https://flagcdn.com/w40/ie.png", dialCode: "+353", maxLength: 9 },
  { code: "IL", name: "Israel", flag: "https://flagcdn.com/w40/il.png", dialCode: "+972", maxLength: 9 },
  { code: "IM", name: "Isle of Man", flag: "https://flagcdn.com/w40/im.png", dialCode: "+44", maxLength: 10 },
  { code: "IN", name: "India", flag: "https://flagcdn.com/w40/in.png", dialCode: "+91", maxLength: 10 },
  { code: "IO", name: "British Indian Ocean Territory", flag: "https://flagcdn.com/w40/io.png", dialCode: "+246", maxLength: 7 },
  { code: "IQ", name: "Iraq", flag: "https://flagcdn.com/w40/iq.png", dialCode: "+964", maxLength: 10 },
  { code: "IR", name: "Iran", flag: "https://flagcdn.com/w40/ir.png", dialCode: "+98", maxLength: 10 },
  { code: "IS", name: "Iceland", flag: "https://flagcdn.com/w40/is.png", dialCode: "+354", maxLength: 7 },
  { code: "IT", name: "Italy", flag: "https://flagcdn.com/w40/it.png", dialCode: "+39", maxLength: 10 },
  { code: "JE", name: "Jersey", flag: "https://flagcdn.com/w40/je.png", dialCode: "+44", maxLength: 10 },
  { code: "JM", name: "Jamaica", flag: "https://flagcdn.com/w40/jm.png", dialCode: "+1876", maxLength: 7 },
  { code: "JO", name: "Jordan", flag: "https://flagcdn.com/w40/jo.png", dialCode: "+962", maxLength: 9 },
  { code: "JP", name: "Japan", flag: "https://flagcdn.com/w40/jp.png", dialCode: "+81", maxLength: 11 },
  { code: "KE", name: "Kenya", flag: "https://flagcdn.com/w40/ke.png", dialCode: "+254", maxLength: 9 },
  { code: "KG", name: "Kyrgyzstan", flag: "https://flagcdn.com/w40/kg.png", dialCode: "+996", maxLength: 9 },
  { code: "KH", name: "Cambodia", flag: "https://flagcdn.com/w40/kh.png", dialCode: "+855", maxLength: 9 },
  { code: "KI", name: "Kiribati", flag: "https://flagcdn.com/w40/ki.png", dialCode: "+686", maxLength: 8 },
  { code: "KM", name: "Comoros", flag: "https://flagcdn.com/w40/km.png", dialCode: "+269", maxLength: 7 },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/w40/kn.png", dialCode: "+1869", maxLength: 7 },
  { code: "KP", name: "North Korea", flag: "https://flagcdn.com/w40/kp.png", dialCode: "+850", maxLength: 10 },
  { code: "KR", name: "South Korea", flag: "https://flagcdn.com/w40/kr.png", dialCode: "+82", maxLength: 10 },
  { code: "KW", name: "Kuwait", flag: "https://flagcdn.com/w40/kw.png", dialCode: "+965", maxLength: 8 },
  { code: "KY", name: "Cayman Islands", flag: "https://flagcdn.com/w40/ky.png", dialCode: "+1345", maxLength: 7 },
  { code: "KZ", name: "Kazakhstan", flag: "https://flagcdn.com/w40/kz.png", dialCode: "+7", maxLength: 10 },
  { code: "LA", name: "Laos", flag: "https://flagcdn.com/w40/la.png", dialCode: "+856", maxLength: 10 },
  { code: "LB", name: "Lebanon", flag: "https://flagcdn.com/w40/lb.png", dialCode: "+961", maxLength: 8 },
  { code: "LC", name: "Saint Lucia", flag: "https://flagcdn.com/w40/lc.png", dialCode: "+1758", maxLength: 7 },
  { code: "LI", name: "Liechtenstein", flag: "https://flagcdn.com/w40/li.png", dialCode: "+423", maxLength: 7 },
  { code: "LK", name: "Sri Lanka", flag: "https://flagcdn.com/w40/lk.png", dialCode: "+94", maxLength: 9 },
  { code: "LR", name: "Liberia", flag: "https://flagcdn.com/w40/lr.png", dialCode: "+231", maxLength: 8 },
  { code: "LS", name: "Lesotho", flag: "https://flagcdn.com/w40/ls.png", dialCode: "+266", maxLength: 8 },
  { code: "LT", name: "Lithuania", flag: "https://flagcdn.com/w40/lt.png", dialCode: "+370", maxLength: 8 },
  { code: "LU", name: "Luxembourg", flag: "https://flagcdn.com/w40/lu.png", dialCode: "+352", maxLength: 9 },
  { code: "LV", name: "Latvia", flag: "https://flagcdn.com/w40/lv.png", dialCode: "+371", maxLength: 8 },
  { code: "LY", name: "Libya", flag: "https://flagcdn.com/w40/ly.png", dialCode: "+218", maxLength: 9 },
  { code: "MA", name: "Morocco", flag: "https://flagcdn.com/w40/ma.png", dialCode: "+212", maxLength: 9 },
  { code: "MC", name: "Monaco", flag: "https://flagcdn.com/w40/mc.png", dialCode: "+377", maxLength: 8 },
  { code: "MD", name: "Moldova", flag: "https://flagcdn.com/w40/md.png", dialCode: "+373", maxLength: 8 },
  { code: "ME", name: "Montenegro", flag: "https://flagcdn.com/w40/me.png", dialCode: "+382", maxLength: 8 },
  { code: "MF", name: "Saint Martin", flag: "https://flagcdn.com/w40/mf.png", dialCode: "+590", maxLength: 9 },
  { code: "MG", name: "Madagascar", flag: "https://flagcdn.com/w40/mg.png", dialCode: "+261", maxLength: 9 },
  { code: "MH", name: "Marshall Islands", flag: "https://flagcdn.com/w40/mh.png", dialCode: "+692", maxLength: 7 },
  { code: "MK", name: "North Macedonia", flag: "https://flagcdn.com/w40/mk.png", dialCode: "+389", maxLength: 8 },
  { code: "ML", name: "Mali", flag: "https://flagcdn.com/w40/ml.png", dialCode: "+223", maxLength: 8 },
  { code: "MM", name: "Myanmar", flag: "https://flagcdn.com/w40/mm.png", dialCode: "+95", maxLength: 9 },
  { code: "MN", name: "Mongolia", flag: "https://flagcdn.com/w40/mn.png", dialCode: "+976", maxLength: 8 },
  { code: "MO", name: "Macao", flag: "https://flagcdn.com/w40/mo.png", dialCode: "+853", maxLength: 8 },
  { code: "MP", name: "Northern Mariana Islands", flag: "https://flagcdn.com/w40/mp.png", dialCode: "+1670", maxLength: 7 },
  { code: "MQ", name: "Martinique", flag: "https://flagcdn.com/w40/mq.png", dialCode: "+596", maxLength: 9 },
  { code: "MR", name: "Mauritania", flag: "https://flagcdn.com/w40/mr.png", dialCode: "+222", maxLength: 8 },
  { code: "MS", name: "Montserrat", flag: "https://flagcdn.com/w40/ms.png", dialCode: "+1664", maxLength: 7 },
  { code: "MT", name: "Malta", flag: "https://flagcdn.com/w40/mt.png", dialCode: "+356", maxLength: 8 },
  { code: "MU", name: "Mauritius", flag: "https://flagcdn.com/w40/mu.png", dialCode: "+230", maxLength: 8 },
  { code: "MV", name: "Maldives", flag: "https://flagcdn.com/w40/mv.png", dialCode: "+960", maxLength: 7 },
  { code: "MW", name: "Malawi", flag: "https://flagcdn.com/w40/mw.png", dialCode: "+265", maxLength: 9 },
  { code: "MX", name: "Mexico", flag: "https://flagcdn.com/w40/mx.png", dialCode: "+52", maxLength: 10 },
  { code: "MY", name: "Malaysia", flag: "https://flagcdn.com/w40/my.png", dialCode: "+60", maxLength: 10 },
  { code: "MZ", name: "Mozambique", flag: "https://flagcdn.com/w40/mz.png", dialCode: "+258", maxLength: 9 },
  { code: "NA", name: "Namibia", flag: "https://flagcdn.com/w40/na.png", dialCode: "+264", maxLength: 9 },
  { code: "NC", name: "New Caledonia", flag: "https://flagcdn.com/w40/nc.png", dialCode: "+687", maxLength: 6 },
  { code: "NE", name: "Niger", flag: "https://flagcdn.com/w40/ne.png", dialCode: "+227", maxLength: 8 },
  { code: "NF", name: "Norfolk Island", flag: "https://flagcdn.com/w40/nf.png", dialCode: "+672", maxLength: 6 },
  { code: "NG", name: "Nigeria", flag: "https://flagcdn.com/w40/ng.png", dialCode: "+234", maxLength: 10 },
  { code: "NI", name: "Nicaragua", flag: "https://flagcdn.com/w40/ni.png", dialCode: "+505", maxLength: 8 },
  { code: "NL", name: "Netherlands", flag: "https://flagcdn.com/w40/nl.png", dialCode: "+31", maxLength: 9 },
  { code: "NO", name: "Norway", flag: "https://flagcdn.com/w40/no.png", dialCode: "+47", maxLength: 8 },
  { code: "NP", name: "Nepal", flag: "https://flagcdn.com/w40/np.png", dialCode: "+977", maxLength: 10 },
  { code: "NR", name: "Nauru", flag: "https://flagcdn.com/w40/nr.png", dialCode: "+674", maxLength: 7 },
  { code: "NU", name: "Niue", flag: "https://flagcdn.com/w40/nu.png", dialCode: "+683", maxLength: 4 },
  { code: "NZ", name: "New Zealand", flag: "https://flagcdn.com/w40/nz.png", dialCode: "+64", maxLength: 9 },
  { code: "OM", name: "Oman", flag: "https://flagcdn.com/w40/om.png", dialCode: "+968", maxLength: 8 },
  { code: "PA", name: "Panama", flag: "https://flagcdn.com/w40/pa.png", dialCode: "+507", maxLength: 8 },
  { code: "PE", name: "Peru", flag: "https://flagcdn.com/w40/pe.png", dialCode: "+51", maxLength: 9 },
  { code: "PF", name: "French Polynesia", flag: "https://flagcdn.com/w40/pf.png", dialCode: "+689", maxLength: 8 },
  { code: "PG", name: "Papua New Guinea", flag: "https://flagcdn.com/w40/pg.png", dialCode: "+675", maxLength: 8 },
  { code: "PH", name: "Philippines", flag: "https://flagcdn.com/w40/ph.png", dialCode: "+63", maxLength: 10 },
  { code: "PK", name: "Pakistan", flag: "https://flagcdn.com/w40/pk.png", dialCode: "+92", maxLength: 10 },
  { code: "PL", name: "Poland", flag: "https://flagcdn.com/w40/pl.png", dialCode: "+48", maxLength: 9 },
  { code: "PM", name: "Saint Pierre and Miquelon", flag: "https://flagcdn.com/w40/pm.png", dialCode: "+508", maxLength: 6 },
  { code: "PN", name: "Pitcairn", flag: "https://flagcdn.com/w40/pn.png", dialCode: "+64", maxLength: 9 },
  { code: "PR", name: "Puerto Rico", flag: "https://flagcdn.com/w40/pr.png", dialCode: "+1", maxLength: 10 },
  { code: "PS", name: "Palestine", flag: "https://flagcdn.com/w40/ps.png", dialCode: "+970", maxLength: 9 },
  { code: "PT", name: "Portugal", flag: "https://flagcdn.com/w40/pt.png", dialCode: "+351", maxLength: 9 },
  { code: "PW", name: "Palau", flag: "https://flagcdn.com/w40/pw.png", dialCode: "+680", maxLength: 7 },
  { code: "PY", name: "Paraguay", flag: "https://flagcdn.com/w40/py.png", dialCode: "+595", maxLength: 9 },
  { code: "QA", name: "Qatar", flag: "https://flagcdn.com/w40/qa.png", dialCode: "+974", maxLength: 8 },
  { code: "RE", name: "Réunion", flag: "https://flagcdn.com/w40/re.png", dialCode: "+262", maxLength: 9 },
  { code: "RO", name: "Romania", flag: "https://flagcdn.com/w40/ro.png", dialCode: "+40", maxLength: 9 },
  { code: "RS", name: "Serbia", flag: "https://flagcdn.com/w40/rs.png", dialCode: "+381", maxLength: 9 },
  { code: "RU", name: "Russia", flag: "https://flagcdn.com/w40/ru.png", dialCode: "+7", maxLength: 10 },
  { code: "SA", name: "Saudi Arabia", flag: "https://flagcdn.com/w40/sa.png", dialCode: "+966", maxLength: 9 },
  { code: "SB", name: "Solomon Islands", flag: "https://flagcdn.com/w40/sb.png", dialCode: "+677", maxLength: 7 },
  { code: "SC", name: "Seychelles", flag: "https://flagcdn.com/w40/sc.png", dialCode: "+248", maxLength: 7 },
  { code: "SD", name: "Sudan", flag: "https://flagcdn.com/w40/sd.png", dialCode: "+249", maxLength: 9 },
  { code: "SE", name: "Sweden", flag: "https://flagcdn.com/w40/se.png", dialCode: "+46", maxLength: 9 },
  { code: "SG", name: "Singapore", flag: "https://flagcdn.com/w40/sg.png", dialCode: "+65", maxLength: 8 },
  { code: "SH", name: "Saint Helena", flag: "https://flagcdn.com/w40/sh.png", dialCode: "+290", maxLength: 4 },
  { code: "SI", name: "Slovenia", flag: "https://flagcdn.com/w40/si.png", dialCode: "+386", maxLength: 8 },
  { code: "SJ", name: "Svalbard and Jan Mayen", flag: "https://flagcdn.com/w40/sj.png", dialCode: "+47", maxLength: 8 },
  { code: "SK", name: "Slovakia", flag: "https://flagcdn.com/w40/sk.png", dialCode: "+421", maxLength: 9 },
  { code: "SL", name: "Sierra Leone", flag: "https://flagcdn.com/w40/sl.png", dialCode: "+232", maxLength: 8 },
  { code: "SM", name: "San Marino", flag: "https://flagcdn.com/w40/sm.png", dialCode: "+378", maxLength: 10 },
  { code: "SN", name: "Senegal", flag: "https://flagcdn.com/w40/sn.png", dialCode: "+221", maxLength: 9 },
  { code: "SO", name: "Somalia", flag: "https://flagcdn.com/w40/so.png", dialCode: "+252", maxLength: 8 },
  { code: "SR", name: "Suriname", flag: "https://flagcdn.com/w40/sr.png", dialCode: "+597", maxLength: 7 },
  { code: "SS", name: "South Sudan", flag: "https://flagcdn.com/w40/ss.png", dialCode: "+211", maxLength: 9 },
  { code: "ST", name: "São Tomé and Príncipe", flag: "https://flagcdn.com/w40/st.png", dialCode: "+239", maxLength: 7 },
  { code: "SV", name: "El Salvador", flag: "https://flagcdn.com/w40/sv.png", dialCode: "+503", maxLength: 8 },
  { code: "SX", name: "Sint Maarten", flag: "https://flagcdn.com/w40/sx.png", dialCode: "+1721", maxLength: 7 },
  { code: "SY", name: "Syria", flag: "https://flagcdn.com/w40/sy.png", dialCode: "+963", maxLength: 9 },
  { code: "SZ", name: "Eswatini", flag: "https://flagcdn.com/w40/sz.png", dialCode: "+268", maxLength: 8 },
  { code: "TC", name: "Turks and Caicos Islands", flag: "https://flagcdn.com/w40/tc.png", dialCode: "+1649", maxLength: 7 },
  { code: "TD", name: "Chad", flag: "https://flagcdn.com/w40/td.png", dialCode: "+235", maxLength: 8 },
  { code: "TF", name: "French Southern Territories", flag: "https://flagcdn.com/w40/tf.png", dialCode: "+262", maxLength: 9 },
  { code: "TG", name: "Togo", flag: "https://flagcdn.com/w40/tg.png", dialCode: "+228", maxLength: 8 },
  { code: "TH", name: "Thailand", flag: "https://flagcdn.com/w40/th.png", dialCode: "+66", maxLength: 9 },
  { code: "TJ", name: "Tajikistan", flag: "https://flagcdn.com/w40/tj.png", dialCode: "+992", maxLength: 9 },
  { code: "TK", name: "Tokelau", flag: "https://flagcdn.com/w40/tk.png", dialCode: "+690", maxLength: 4 },
  { code: "TL", name: "Timor-Leste", flag: "https://flagcdn.com/w40/tl.png", dialCode: "+670", maxLength: 8 },
  { code: "TM", name: "Turkmenistan", flag: "https://flagcdn.com/w40/tm.png", dialCode: "+993", maxLength: 8 },
  { code: "TN", name: "Tunisia", flag: "https://flagcdn.com/w40/tn.png", dialCode: "+216", maxLength: 8 },
  { code: "TO", name: "Tonga", flag: "https://flagcdn.com/w40/to.png", dialCode: "+676", maxLength: 5 },
  { code: "TR", name: "Turkey", flag: "https://flagcdn.com/w40/tr.png", dialCode: "+90", maxLength: 10 },
  { code: "TT", name: "Trinidad and Tobago", flag: "https://flagcdn.com/w40/tt.png", dialCode: "+1868", maxLength: 7 },
  { code: "TV", name: "Tuvalu", flag: "https://flagcdn.com/w40/tv.png", dialCode: "+688", maxLength: 5 },
  { code: "TW", name: "Taiwan", flag: "https://flagcdn.com/w40/tw.png", dialCode: "+886", maxLength: 9 },
  { code: "TZ", name: "Tanzania", flag: "https://flagcdn.com/w40/tz.png", dialCode: "+255", maxLength: 9 },
  { code: "UA", name: "Ukraine", flag: "https://flagcdn.com/w40/ua.png", dialCode: "+380", maxLength: 9 },
  { code: "UG", name: "Uganda", flag: "https://flagcdn.com/w40/ug.png", dialCode: "+256", maxLength: 9 },
  { code: "UM", name: "United States Minor Outlying Islands", flag: "https://flagcdn.com/w40/um.png", dialCode: "+1", maxLength: 10 },
  { code: "US", name: "United States", flag: "https://flagcdn.com/w40/us.png", dialCode: "+1", maxLength: 10 },
  { code: "UY", name: "Uruguay", flag: "https://flagcdn.com/w40/uy.png", dialCode: "+598", maxLength: 8 },
  { code: "UZ", name: "Uzbekistan", flag: "https://flagcdn.com/w40/uz.png", dialCode: "+998", maxLength: 9 },
  { code: "VA", name: "Vatican City", flag: "https://flagcdn.com/w40/va.png", dialCode: "+39", maxLength: 10 },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/w40/vc.png", dialCode: "+1784", maxLength: 7 },
  { code: "VE", name: "Venezuela", flag: "https://flagcdn.com/w40/ve.png", dialCode: "+58", maxLength: 10 },
  { code: "VG", name: "British Virgin Islands", flag: "https://flagcdn.com/w40/vg.png", dialCode: "+1284", maxLength: 7 },
  { code: "VI", name: "U.S. Virgin Islands", flag: "https://flagcdn.com/w40/vi.png", dialCode: "+1340", maxLength: 7 },
  { code: "VN", name: "Vietnam", flag: "https://flagcdn.com/w40/vn.png", dialCode: "+84", maxLength: 10 },
  { code: "VU", name: "Vanuatu", flag: "https://flagcdn.com/w40/vu.png", dialCode: "+678", maxLength: 7 },
  { code: "WF", name: "Wallis and Futuna", flag: "https://flagcdn.com/w40/wf.png", dialCode: "+681", maxLength: 6 },
  { code: "WS", name: "Samoa", flag: "https://flagcdn.com/w40/ws.png", dialCode: "+685", maxLength: 7 },
  { code: "YE", name: "Yemen", flag: "https://flagcdn.com/w40/ye.png", dialCode: "+967", maxLength: 9 },
  { code: "YT", name: "Mayotte", flag: "https://flagcdn.com/w40/yt.png", dialCode: "+262", maxLength: 9 },
  { code: "ZA", name: "South Africa", flag: "https://flagcdn.com/w40/za.png", dialCode: "+27", maxLength: 9 },
  { code: "ZM", name: "Zambia", flag: "https://flagcdn.com/w40/zm.png", dialCode: "+260", maxLength: 9 },
  { code: "ZW", name: "Zimbabwe", flag: "https://flagcdn.com/w40/zw.png", dialCode: "+263", maxLength: 9 },
];
